import type { PreviewPage, WebsiteConfig } from '../../../types/website-config';

export type GeneratorPage = PreviewPage;

export function pageSeoTitle(config: WebsiteConfig, page: GeneratorPage): string {
  const { copy, seo } = config;
  switch (page) {
    case 'about':
      return `${copy.aboutIntro} | ${copy.localTitle}`;
    case 'services':
      return `Diensten | ${copy.localTitle}`;
    case 'contact':
      return `Contact | ${copy.localTitle}`;
    case 'privacy':
      return `Privacybeleid | ${config.slug.domain.replace('.starlocal.nl', '')}`;
    default:
      return seo.title;
  }
}

export function pageHeading(config: WebsiteConfig, page: GeneratorPage): string {
  switch (page) {
    case 'about':
      return config.copy.aboutIntro;
    case 'services':
      return 'Onze diensten';
    case 'contact':
      return `Contact — ${config.copy.localTitle}`;
    case 'privacy':
      return 'Privacybeleid';
    default:
      return config.seo.h1;
  }
}

export type { PageSeoBundle } from './seo';
export { buildAllPageSeo, buildPageSeo, TENANT_PAGE_PATHS, tenantPagePath } from './seo';
export { WebsiteGeneratorService, websiteGenerator } from './website-generator.service';
export type { GeneratedWebsiteResult, WebsiteGenerationSummary } from './website-generator.service';
export {
  autoGenerateWebsite,
  verifyAutoGeneratedWebsite,
  validateForAutoGenerate,
  syncGeneratedToWebsiteList,
  type AutoGenerateSummary,
  type AutoGenerateResult,
  type AutoGenerateResponse,
} from './auto-generate.service';
export { renderGeneratedWebsite, renderGeneratedWebsiteFromConfig, renderExampleDomainBar } from './template';
export type { RenderWebsiteOptions } from './template';
export { buildTenantPageDocument, buildAllTenantDocuments } from './document';
export { buildTenantManifest, TENANT_MANIFEST_PATH } from './manifest';
export { buildTenantFavicon, TENANT_FAVICON_PATH } from './favicon';
export { buildTenantSitemap, TENANT_DOCUMENT_PATHS, TENANT_ROBOTS_PATH, TENANT_SITEMAP_PATH } from './sitemap';
export { buildTenantRobots } from './robots';
