/**
 * Automatic Website Generator test — Bakkerij De Markt
 * Run: npm run test:generate
 */
import { autoGenerateWebsite, verifyAutoGeneratedWebsite } from '../src/lib/builder/generator/auto-generate.service.ts';
import { createBakkerijDeMarktFiles, createBakkerijDeMarktState } from '../src/lib/publish/fixtures/bakkerij-de-markt.ts';
import { WEBSITE_PAGES } from '../src/types/website-config.ts';

const state = createBakkerijDeMarktState();
state.contact.city = 'Breda';
state.location.gemeenteNaam = 'Breda';
const files = createBakkerijDeMarktFiles();
files.logoUrl =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAD0lEQVR42mP8z5/wHwAF';
files.logoName = 'logo-bakkerij.png';

const result = autoGenerateWebsite(state, files);

if (!result.ok) {
  console.error('FAIL: generatie mislukt', result.errors);
  process.exit(1);
}

const { generated, summary } = result;
const verification = verifyAutoGeneratedWebsite(generated);
const homeHtml = generated.pages.home ?? '';
const contactHtml = generated.pages.contact ?? '';

const checks: [string, boolean][] = [
  ['5 pagina\'s gegenereerd', summary.pageCount === 5],
  ['Homepage', (generated.pages.home ?? '').length > 100],
  ['Over ons', (generated.pages.about ?? '').length > 100],
  ['Diensten', (generated.pages.services ?? '').length > 100],
  ['Contact', contactHtml.length > 100],
  ['Privacy', (generated.pages.privacy ?? '').length > 100],
  ['Menu (tenant-nav)', homeHtml.includes('tenant-nav')],
  ['Privacy in menu', homeHtml.includes('data-preview-page="privacy"') || homeHtml.includes('href="/privacy/"')],
  ['Footer', homeHtml.includes('tenant-footer')],
  ['Footer telefoonlink', homeHtml.includes('tel:')],
  ['Footer copyright', homeHtml.includes('Bakkerij De Markt')],
  ['SEO titel', Boolean(summary.seoTitle)],
  ['Meta description', Boolean(summary.metaDescription)],
  ['Open Graph titel', Boolean(summary.ogTitle)],
  ['Canonical', Boolean(summary.canonicalUrl)],
  ['JSON-LD LocalBusiness', summary.hasJsonLd],
  ['robots.txt', summary.hasRobots],
  ['sitemap.xml', summary.hasSitemap],
  ['Contact mailto', contactHtml.includes('mailto:')],
  ['Contact Google Maps', contactHtml.includes('Google Maps')],
  ['Contactformulier', contactHtml.includes('tenant-form') && contactHtml.includes('type="submit"')],
  ['Kaartplaceholder', contactHtml.includes('tenant-map-placeholder')],
  ['Verificatie', verification.valid],
];

let failed = 0;
console.log('\n=== Bakkerij De Markt — automatische website generator ===\n');
console.log(`Bedrijf: ${summary.businessName}`);
console.log(`Domein: ${summary.domain}`);
console.log(`Pagina's: ${WEBSITE_PAGES.join(', ')}\n`);

for (const [label, ok] of checks) {
  console.log(`${ok ? 'OK' : 'FAIL'} ${label}`);
  if (!ok) failed += 1;
}

if (verification.missing.length) {
  console.log('\nOntbrekend:', verification.missing.join(', '));
}

console.log(`\nMenu: ${summary.menuItems.join(' · ')}`);
console.log(`SEO titel: ${summary.seoTitle}`);

if (failed > 0) {
  console.error(`\n${failed} controle(s) mislukt.`);
  process.exit(1);
}

console.log('\nAlle controles geslaagd.\n');
